### ISSUE TITLE
ADD README OR DESCRIPTION IN YOUR PROJECT

### ISSUE THREAD

**Issue by xshshahab** [AhmadAltamash/Auto-Mobile-Servicing#2]
Ensure to add a well-structured README or project description to provide clear guidance on the application's functionality, setup instructions, and any dependencies. This will help future developers and users easily understand the project’s purpose and how to contribute or deploy it.

**Comment by AhmadAltamash** [comment]
Yes.., at the very moment project completes, i'll add README
